### ISSUE TITLE
Broken as of 9.0.1

### ISSUE THREAD

**Issue by PastelBirb** [BloodDragon2580/Healium#1]
With the release of the Shadowlands Pre-Patch, the addon is unfortunately no longer working. Clicking on the mini-map icon does nothing and going into interface -> addons -> healium shows nothing but an empty box. 

![image](https://user-images.githubusercontent.com/72849086/95945020-9bdc1480-0db7-11eb-9fed-d0cd196951b8.png)

Sidenote: I truly appreciate you intending to work on this addon! I have limited motor function in my right arm, and healium by far has been the easiest addon to use for healing.

**Comment by BloodDragon2580** [comment]
I will test it so fast i can. I have many other Addons that must be updatet, so i will fix it in the next days i think. In Germany we become today the PrePatch so i can look on this.

**Comment by BloodDragon2580** [comment]
Test this version: https://github.com/BloodDragon2580/Healium/releases/download/Healium.v3.0.0/Healium.v3.0.0.zip

**Comment by PastelBirb** [comment]
As of v3 Healium is back! The only issue I have tested and seen thus far is the backdrop for titles and the menu is not there, but is an overall minor issue 
![image](https://user-images.githubusercontent.com/72849086/96049964-d8a31c80-0e46-11eb-8895-d4d04c15e3c8.png)

Once again, thank you very very much for help keeping this addon alive

**Comment by BloodDragon2580** [comment]
I will test tomorrow a other Option.
