### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by beetpt** [BloodDragon2580/Healium#2]
Great work and ty for keep this addon up
Paladin Holy Shock and some other spells give lua error in group only that i see

Message: Interface\AddOns\Healium\Healium.lua:421: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Thu Oct 15 01:35:23 2020
Count: 162
Stack: Interface\AddOns\Healium\Healium.lua:421: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@Interface\AddOns\Healium\Healium.lua"]:421: in function `Healium_UpdateUnitThreat'
[string "@Interface\AddOns\Healium\Healium.lua"]:1152: in function <Interface\AddOns\Healium\Healium.lua:1110>

Locals: unitName = "party1"
NamePlate = HealiumPartyFrame_HeaderUnitButton2 {
 CalculateAction = <function> defined @Interface\FrameXML\SecureTemplates.lua:582
 ManaBar = <unnamed> {
 }
 HealthBar = <unnamed> {
 }
 CurseBar = <unnamed> {
 }
 debuffColor = <table> {
 }
 PredictBar = <unnamed> {
 }
 showMana = true
 HasRole = true
 TargetUnit = "party1"
 AggroBar = <unnamed> {
 }
 buttons = <table> {
 }
 buffs = <table> {
 }
 0 = <userdata>
 Buff = <table> {
 }
}
status = 3
r = 0.999998
g = 0
b = 0
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0.999998
(*temporary) = 0
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
IsClassic = false

**Comment by BloodDragon2580** [comment]
Please test version [3.0.1](https://github.com/BloodDragon2580/Healium/releases/download/Healium.v3.0.1/Healium.v3.0.1.zip)

**Comment by beetpt** [comment]
ok i will do it, but later i'm at work now 👍 ty

**Comment by BloodDragon2580** [comment]
Please Test [3.0.2](https://github.com/BloodDragon2580/Healium/releases/download/Healium.v3.0.2/Healium.v3.0.2.zip)

**Comment by BloodDragon2580** [comment]
Alternativ copie and past this:  " **/console scripterrors 0** " on your chat InGame. Without the "".

**Comment by beetpt** [comment]
i use console commands but, i like to know issues so i  can report them and you can improve addon.
I will this fixed version ty for your excelent work.

**Comment by BloodDragon2580** [comment]
No Problem mate.

**Comment by beetpt** [comment]
Message: Interface\AddOns\Healium\HealiumSpells.lua:290: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Thu Oct 15 12:24:30 2020
Count: 2
Stack: Interface\AddOns\Healium\HealiumSpells.lua:290: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@Interface\AddOns\Healium\HealiumSpells.lua"]:290: in function `Healium_ShowDebuffButtons'
[string "@Interface\AddOns\Healium\HealiumUnitFrames.lua"]:946: in function `Healium_UpdateUnitBuffs'
[string "@Interface\AddOns\Healium\Healium.lua"]:1125: in function <Interface\AddOns\Healium\Healium.lua:1094>

Locals: Profile = <table> {
 SpellNames = <table> {
 }
 SpellTypes = <table> {
 }
 SpellIcons = <table> {
 }
 ButtonCount = 13
 IDs = <table> {
 }
 SpellRanks = <table> {
 }
}
frame = HealiumTargetFrame_Header {
 CalculateAction = <function> defined @Interface\FrameXML\SecureTemplates.lua:582
 ManaBar = <unnamed> {
 }
 HealthBar = <unnamed> {
 }
 CurseBar = <unnamed> {
 }
 PredictBar = <unnamed> {
 }
 debuffColor = <table> {
 }
 isCustom = true
 TargetUnit = "target"
 AggroBar = <unnamed> {
 }
 hasDebuf = true
 buttons = <table> {
 }
 buffs = <table> {
 }
 0 = <userdata>
 Buff = <table> {
 }
}
debuffTypes = <table> {
 Magic = true
}
(for index) = 12
(for limit) = 13
(for step) = 1
i = 12
button = HealiumTargetFrame_Header_Heal12 {
 0 = <userdata>
 cooldown = <unnamed> {
 }
 index = 12
 CurseBar = <unnamed> {
 }
 id = 56
 CalculateAction = <function> defined @Interface\FrameXML\SecureTemplates.lua:582
 icon = <unnamed> {
 }
 TimeSinceLastUpdate = 0
}
spell = "Cleanse"
cure = <table> {
 CanCurePoison = true
 CanCureMagic = true
 CanCureDisease = true
}
flag = true
debuffColor = <table> {
 b = 1
 g = 0.600000
 r = 0.200000
}
curseBar = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0.200000
(*temporary) = 0.600000
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
Cures = <table> {
 Cleanse Toxins = <table> {
 }
 Cleanse = <table> {
 }
}
GetCanCureMagic = <function> defined @Interface\AddOns\Healium\HealiumSpells.lua:210

**Comment by beetpt** [comment]
same error i think

**Comment by BloodDragon2580** [comment]
What are you doing that the error comes. For me it works without any errors so far.

**Comment by BloodDragon2580** [comment]
So check this update now^^ i hope its now fixed. [3.0.3](https://github.com/BloodDragon2580/Healium/releases/download/Healium.v3.0.3/Healium.v3.0.3.zip)

**Comment by beetpt** [comment]
i will, i can´t log in now because server problems :(

ty

**Comment by BloodDragon2580** [comment]
Have been trying for 4 hours

**Comment by BloodDragon2580** [comment]
Here a little fix on Healium.lua file. Download [3.0.4](https://github.com/BloodDragon2580/Healium/releases/download/Healium.v3.0.4/Healium.v3.0.4.zip)

**Comment by beetpt** [comment]
Message: Interface\AddOns\MaxDps\Buttons.lua:247: attempt to call global 'ActionButton_GetPagedID' (a nil value)
Time: Thu Oct 15 19:05:46 2020
Count: 2
Stack: Interface\AddOns\MaxDps\Buttons.lua:247: attempt to call global 'ActionButton_GetPagedID' (a nil value)
[string "@Interface\AddOns\MaxDps\Buttons.lua"]:247: in function `AddStandardButton'
[string "@Interface\AddOns\MaxDps\Buttons.lua"]:438: in function `FetchBlizzard'
[string "@Interface\AddOns\MaxDps\Buttons.lua"]:287: in function `Fetch'
[string "@Interface\AddOns\MaxDps\Core.lua"]:92: in function `EnableRotation'
[string "@Interface\AddOns\MaxDps\Core.lua"]:226: in function `?'
[string "@Interface\AddOns\AskMrRobot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:145: in function <...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
[string "@Interface\AddOns\AskMrRobot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:90: in function `Fire'
[string "@Interface\AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by beetpt** [comment]
no errors now, only dispell part now with problems

**Comment by BloodDragon2580** [comment]
what for problems can you make a screen or else?

**Comment by beetpt** [comment]
i can hear only the bell to use dispell but dispell button highlight warning don't show and healthbars only show sometimes and very rare

**Comment by beetpt** [comment]
now i can see healthbars for dispells, i can't see only the button highlight warnig
you did a great and fast improve of this addon
great job

**Comment by BloodDragon2580** [comment]
Thx, so i close this issue now. You can open a new one when you find everything or else^^.
